### ISSUE TITLE
Problem with non root user

### ISSUE THREAD

**Issue by ulvida** [systemli/ansible-role-bind9#1]
Hello, when I execute your role with a user with sudo privilegies, but not being root itself, it gives an error at [this task]( https://github.com/systemli/ansible-role-bind9/blob/master/tasks/main.yml#L35).

```
- name: check validity of named.conf
  command: named-checkconf
  register: bind9_reg_named_checkconf
  become: true
  become_user: "{{ bind9_user }}"
changed_when: False
```
because of write access to temp files between two remote non root users. There are ways recommended to avoid this error, I couldn't go further.

**Comment by xshadow** [comment]
Hey ulvida, 

can you please pass the error message. I assume it's  a privilege error.

You can set: 

`allow_world_readable_tmpfiles=true` in your `ansible.cfg`.

**Comment by ulvida** [comment]
Danke shön, xshadow. 

> can you please pass the error message. I assume it's a privilege error.

Yes, this was the error: 
```
TASK [systemli.bind9 : check validity of named.conf] ***************************
fatal: [guabiyu.interior.edu.uy]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1541427609.46-41842135367009/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1541427609.46-41842135367009/AnsiballZ_command.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
	to retry, use: --limit @/home/ulvida/tech/interior/config/site.retry
```
>You can set: allow_world_readable_tmpfiles=true in your ansible.cfg.

Yes, it was the way I solved. I have no direct unix users except sysadmin in these servers, so it's not a security problem.
