### ISSUE TITLE
Initial commit hash?

### ISSUE THREAD

**Issue by ulvida** [systemli/ansible-role-bind9#53]
Hello, I was trying to prepare a PR, and I came to [this problem](https://github.com/UdelaRInterior/ansible-role-bind9/issues/10), that our repos, despite being ours forked from yours seem no longer related.

**Comment by xshadow** [comment]
The initial commit hash is: 

```
commit 101b5bdb3028abdc61336d04acf0533ece1f567a
Author: doobry <doobry@systemli.org>
Date:   Wed Apr 18 21:28:54 2018 +0200

    Initial commit
```

Maybe you have to fork our repo again and add your changes on top of this.

**Comment by xshadow** [comment]
Could it be related, that we renamed our branches from "master" to "main" and this is somehow not reflected in your git / git configuration?

**Comment by ulvida** [comment]
> The initial commit hash is:
> 
> ```
> commit 101b5bdb3028abdc61336d04acf0533ece1f567a
> Author: doobry <doobry@systemli.org>
> Date:   Wed Apr 18 21:28:54 2018 +0200
> 
>     Initial commit
> ```
Strange. That's [the hash we have in our fork for initial commit](https://github.com/UdelaRInterior/ansible-role-bind9/commit/101b5bdb3028abdc61336d04acf0533ece1f567a). In your upstream repo, [the present initial commit has another hash](https://github.com/systemli/ansible-role-bind9/commit/cd46735c995ee4a52c6f5672be5a0167e62fd4f5). The commit with the hash you mention [is still present in the repo](https://github.com/systemli/ansible-role-bind9/commit/101b5bdb3028abdc61336d04acf0533ece1f567a), but it's not linked to any branch.   Maybe on some way one of you amended this commit?

> 
> Maybe you have to fork our repo again and add your changes on top of this.

We, proud french, use to say: _Les grands esprits se rencontrent_. It's [what I did](ulvida/ansible-role-bind9), and proposed you PR #54 (that may take some time to be digested).

**Comment by ulvida** [comment]
> Could it be related, that we renamed our branches from "master" to "main" and this is somehow not reflected in your git / git configuration?

I don't think so. I did already noticed your switch from master to main, and reflected it in my fork with an upstream-main branch, initially identical to your main. I remember I successfully  did a `git pull upstream main` to this branch. And now it refused for unrelated histories. So I suspect something changed from first to second time in main branch or related fork.
