### ISSUE TITLE
dynamic zone files are broken in version 1.1.0

### ISSUE THREAD

**Issue by yannik-b** [systemli/ansible-role-bind9#6]
With ansible-role-bind9 version `1.1.0` (latest release) and `dynamic zone files`, I get the following error:
```
TASK [systemli.bind9 : create dynamic bind9 zone files] **
failed: [dns1] (item={'name': 'example.com', 'serial': 2019121301, 'admin': 'hostmaster.example.com',
'ns_records': ['ns1.example.com', 'ns2.example.com'], 'a_records': ['1.2.3.4'], 'aaaa_records': ['1:2:3:4::8'],
'mx_records': [{'priority': 10, 'name': 'mx.example.com'}], 'rrs': [{'label': 'www', 'type': 'CNAME',
'rdata': 'example.com.'}]}) => {"ansible_loop_var": "item", "changed": false, "item": {"a_records": ["1.2.3.4"],
"aaaa_records": ["1:2:3:4::8"], "admin": "hostmaster.example.com", "mx_records": [{"name": "mx.example.com",
"priority": 10}], "name": "example.com", "ns_records": ["ns1.example.com", "ns2.example.com"], "rrs": [{"label": "www",
"rdata": "example.com.", "type": "CNAME"}], "serial": 2019121301},
"msg": "AnsibleUndefinedVariable: 'zone' is undefined"}
```
The problem is, in `tasks/main.yml` `bind9_zones_dynamic` is passed in `item` variable for the template. The template `templates/bind/zones/db.template.j2` tries to find the zone data in `zone`, but `item` is never been cast to `zone`. 
In branch `master` is a new version of the template available which works, but it isn't in Ansible Galaxy yet.

**Comment by t2d** [comment]
Thank you for bringing this up. We forgot to make a new release. There is now `1.2.0`. Hope this helps!
