### ISSUE TITLE
Problems with DDNS updating zone file due to access restrictions

### ISSUE THREAD

**Issue by 0xMattijs** [systemli/ansible-role-bind9#60]
This Ansible role writes zone files to a hard coded `/etc/bind/zones` directory, which causes problems on systems with mandatory access control such as Apparmor. The profile for Apparmor does not allow the BIND process to create the necessary journal files and update the zone files under `/etc/bind/zones`.

I have created a PR to fix this issue: #59

**Comment by doobry-systemli** [comment]
Fixed by #59, thanks @0xMattijs
