### ISSUE TITLE
Support for port in forwarders

### ISSUE THREAD

**Issue by codezninja** [systemli/ansible-role-bind9#61]
New to ansible and bind so forgive me if this is an easy question. I'm trying to setup a consul forwarder and it requires that I also add port to the named.config based on this documentation https://developer.hashicorp.com/consul/tutorials/networking/dns-forwarding#zone-file. Now looking through the template. It seems like it only supports ip address. Is there a way to override the default template or even add support to the default template to add a port?

https://github.com/systemli/ansible-role-bind9/blob/d6b74e219be7cf3e87a68e8910ede6bda0e2415f/templates/bind/named.conf.local.j2#L72-L76

**Comment by 0xMattijs** [comment]
You could simply add the port keyword to your `bind9_forward_servers` like this:
```
    bind9_forward_servers:
      - 1.2.3.4 port 5353
      - 8.8.8.8
```
This will result into the following (valid) configuration section in `named.conf.options`:
```
  forwarders {
          1.2.3.4 port 5353;
          8.8.8.8;
      };
```

**Comment by codezninja** [comment]
Thank you so much that worked.
