### ISSUE TITLE
question: does this role have a check syntax before restart mecanism 

### ISSUE THREAD

**Issue by LuisBL** [systemli/ansible-role-bind9#65]
does ansible-role-bind9 use a mecanism to check that the syntax zone is ok ? like:

`named-checkzone mysite.com /etc/bind/zones/db.mysite.com`

We had the bad experience to restart a bind9 server with brocken db.mysite.com syntax, bind was not restarting.

Regards

**Comment by t2d** [comment]
Hi. These checks are currently not implemented. However, it should be very easy to add your command as a `validate` [statement](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#parameter-validate) [to the corresponding tasks](https://github.com/systemli/ansible-role-bind9/blob/main/tasks/main.yml#L305), for example. PRs very welcome!
