### ISSUE TITLE
Contents of `update_keyfile` put into `named.conf.options`

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/ansible-role-bind9#69]
Apparently PR #59 introduced a bug. In particular, the following lines result in the content of keyfiles from Ansible variable `update_keyfiles` being put into `named.conf.options`:

https://github.com/systemli/ansible-role-bind9/pull/59/files#diff-640c3aa35ba9f176f655e3355b69e72be6b81ad0f4e94c2fc08dc0041f2b38d6R75-R85

@0xMattijs since you introduced this, could you take a look?

**Comment by t2d** [comment]
If this breaks our workflow, we should just revert and give it another try later. Just my 2¢
